version: 2

jobs:
  build:
    docker:
      - image: trevorj/circleci-builder:latest
    working_directory: /app

    steps:
      - checkout
      - run:
          name: checkout-submodules
          command: |
            set -eo pipefail
            git submodule sync
            git submodule update --init

      - setup_remote_docker:
          version: 17.07.0-ce

      - run:
          context: org-global
          name: build
          command: |
            set -eo pipefail
            exec make -j8

      - run:
          context: org-global
          name: test
          command: |
            set -eo pipefail
            exec make test

      - deploy:
          context: org-global
          name: docker-login
          command: |
            exec docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"

      - deploy:
          context: org-global
          name: push
          command: |
            set -eo pipefail
            case "$CIRCLE_BRANCH" in
                master)
                  exec make -j8 push ;;
            esac
